/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/lib/theme.ts
 * Command: astryx theme build src/lib/theme.ts
 * Generated: 2026-08-04T19:38:18.283Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
