/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/lib/theme.ts
 * Command: astryx theme build src/lib/theme.ts
 * Generated: 2026-08-04T19:38:18.285Z
 */

/// <reference path="./ludavia.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const ludaviaTheme: DefinedTheme;
